### ISSUE TITLE
两个优化

### ISSUE THREAD

**Issue by sunchenguang** [lilongllong/netease-music-react#7]
1.  给个入口输入用户名，就出来用户自己的歌单。用户名应该是唯一的，但是没找到简单的办法直接获取`userid`
2. 音乐播放完成后自动向下切换，或者提供循环，随机，顺序的播放方式

**Comment by lilongllong** [comment]
第一个优化我在考虑下，我希望解析出网易的登录方式。
第二个优化我会尽快做。

**Comment by lilongllong** [comment]
@sunchenguang 你好，对于你提出的优化问题，我做出了相应的design，详情见README
对于userid，我是通过登录网易云音乐，查看网页源码找到的:smile:
![image](https://cloud.githubusercontent.com/assets/8185964/22723882/f50692c6-edfc-11e6-80f5-0a25cca108ad.png)

**Comment by sunchenguang** [comment]
厉害，我在做你这个项目的Dva版，看能搞成啥样
